// Item overview enum

export enum EItem {
  OIL = "Oil",
  INCUBATOR = "Incubator",
  SCARAB = "Scarab",
  FOSSIL = "Fossil",
  RESONATOR = "Resonator",
  ESSENCE = "Essence",
  DIVINATION_CARD = "DivinationCard",
  SKILL_GEM = "SkillGem",
  BASE_TYPE = "BaseType",
  HELMET_ENCHANT = "HelmetEnchant",
  UNIQUE_MAP = "UniqueMap",
  MAP = "Map",
  UNIQUE_JEWEL = "UniqueJewel",
  UNIQUE_FLASK = "UniqueFlask",
  UNIQUE_WEAPON = "UniqueWeapon",
  UNIQUE_ARMOUR = "UniqueArmour",
  UNIQUE_ACCESSORY = "UniqueAccessory",
  BEAST = "Beast",
  VIALS = "Vials",
  DELIRIUM_ORBS = "DeliriumOrbs",
  OMENS = "Omens",
  UNIQUE_RELIC = "UniqueRelic",
  CLUSTER_JEWEL = "ClusterJewel",
  BLIGHTED_MAPS = "BlightedMaps",
  BLIGHT_RAVAGED_MAPS = "BlightRavagedMaps",
  INVITATIONS = "Invitations",
  MEMORIES = "Memories",
  COFFINS = "Coffins",
  ALLFLAME_EMBERS = "AllflameEmbers",
}